name: build and deploy hugo site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Clean up exampleSite (if exists)
        run: |
          if [ -d "./themes/gokarna/exampleSite" ]; then
            echo "Removing exampleSite directory to avoid symbolic link issues..."
            rm -rf ./themes/gokarna/exampleSite
          else
            echo "exampleSite directory does not exist, skipping cleanup."
          fi

      - name: Update theme
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BUILD_TOKEN }}
          external_repository: gndpwnd/gndpwnd.github.io
          publish_dir: ./public
          publish_branch: published
        #   cname: example.com
